"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = config('SECRET_KEY', default='django-insecure-v5m=4q4)lopw%dfij@%szje+6nugh@gfdqy3d*d%u$xju5uf6o')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'weather',
    'users',
    'rest_framework',
    'rest_framework_simplejwt' # <-- Dependencia para los tokens (JWT)
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8, # Mínimo de 8 caracteres
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración de JWT

from datetime import timedelta

# Definir el tipo de autenticación que se va a usar
AUTH_TYPE = 'JWT'

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication", # Para JWT
        "rest_framework.authentication.SessionAuthentication", # Para sesiones
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:3000",
    "http://127.0.0.1:5173",
]

EMBLEM_PHOTO_BASE_URL = config(
    "EMBLEM_PHOTO_BASE_URL",
    default="https://cdn.example.com/emblems/",
)

CITY_PHOTO_BASE_URL = config(
    "CITY_PHOTO_BASE_URL",
    default="https://cdn.example.com/cities/",
)

# Habilitar Argon2 en Django para mayor seguridad 
# https://docs.djangoproject.com/en/5.1/topics/auth/passwords/#using-argon2-with-django
# Comando:
# python -m pip install django[argon2]
# Una vez instalado, modificar PASSWORD_HASHERS para listar "Argon2PasswordHasher":
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.PBKDF2PasswordHasher", # Por defecto
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher", # El más frecuente
    "django.contrib.auth.hashers.Argon2PasswordHasher", # Más seguro
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher", # Opcional
    "django.contrib.auth.hashers.ScryptPasswordHasher", # Opcional
]

# --- CONFIGURACION DE EMAIL --- 
# Método 1
# Configuración de Email para Gmail (Desarrollo)
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "vampileo28@gmail.com"
EMAIL_HOST_PASSWORD = "mi_contrasena" # NO usar contraseña normal
DEFAULT_FROM_EMAIL = "vampileo28@gmail.com" 

# URL base de la aplicación
FRONTEND_URL = "http://localhost:3000" # Para desarrollo
# FRONTEND_URL = "https://tudominio.com" # Para producion

# Método 2
# SendGrid (Produccion)
# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = "smtp.sendgrid.net"
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = "apikey"
# EMAIL_HOST_PASSWORD = "tu_sendgrid_api_key" 
# DEFAULT_FROM_EMAIL = "noreply@atmos.com"
# 
# FRONTEND_URL = "https://atmos.com" 
#
# Si se usa SendGrid, utilizamos este comando:
# pip install sendgrid
# 
# Para desarrollo con variables de entorno
# pip install python-decouple 