# Generated by Django 5.1.15 on 2025-12-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_weatherobservation_options_city_altitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherobservation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
