# Generated by Django 5.1.15 on 2025-12-05 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_alter_weatherobservation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherobservation',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='weather.city'),
        ),
    ]
