# Generated by Django 5.1.15 on 2025-12-04 09:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherobservation',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Observación Meteorológica', 'verbose_name_plural': 'Datos Meteorológicos'},
        ),
        migrations.AddField(
            model_name='city',
            name='altitud',
            field=models.FloatField(blank=True, help_text='Metros sobre el nivel del mar', null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='latitud',
            field=models.FloatField(default=0, help_text='Latitud de la ciudad'),
        ),
        migrations.AddField(
            model_name='city',
            name='longitud',
            field=models.FloatField(default=0, help_text='Longitud de la ciudad'),
        ),
        migrations.AddField(
            model_name='weatherobservation',
            name='cloud_cover',
            field=models.FloatField(blank=True, default=0, help_text='Porcentaje de cobertura nubosa', null=True),
        ),
        migrations.AddField(
            model_name='weatherobservation',
            name='dew_point',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='weatherobservation',
            name='heat_index',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='weatherobservation',
            name='humidity',
            field=models.FloatField(default=0, help_text='Humedad relativa en procentaje (0-100)'),
        ),
        migrations.AddField(
            model_name='weatherobservation',
            name='max_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherobservation',
            name='min_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherobservation',
            name='precipitation',
            field=models.FloatField(default=0, help_text='Precipitación en mm (milímetros)'),
        ),
        migrations.AddField(
            model_name='weatherobservation',
            name='pressure',
            field=models.FloatField(default=0, help_text='Presión atmosférica en hPa (hectopascal)'),
        ),
        migrations.AddField(
            model_name='weatherobservation',
            name='visibility',
            field=models.FloatField(blank=True, default=0, help_text='Visibilidad en km', null=True),
        ),
        migrations.AddField(
            model_name='weatherobservation',
            name='wind_chill',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='weatherobservation',
            name='wind_direction',
            field=models.FloatField(default=0, help_text='Dirección del viento en grados (0-360)'),
        ),
        migrations.AddField(
            model_name='weatherobservation',
            name='wind_gust',
            field=models.FloatField(blank=True, default=0, help_text='Ráfaga máxima de viento en km/h', null=True),
        ),
        migrations.AddField(
            model_name='weatherobservation',
            name='wind_speed',
            field=models.FloatField(default=0, help_text='Velocidad del viento en km/h (kilómetros por hora)'),
        ),
        migrations.AlterField(
            model_name='weatherobservation',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Observaciones en ciudades+', to='weather.city'),
        ),
        migrations.AlterField(
            model_name='weatherobservation',
            name='temperature',
            field=models.FloatField(help_text='Temperatura en grados Celsius'),
        ),
        migrations.AlterField(
            model_name='weatherobservation',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='weatherobservation',
            index=models.Index(fields=['-timestamp'], name='weather_wea_timesta_8f96b4_idx'),
        ),
    ]
