# Generated by Django 5.1.15 on 2025-12-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='weatherobservation',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Weather Observations'},
        ),
        migrations.AddField(
            model_name='weatherobservation',
            name='condition',
            field=models.CharField(default='Parcialmente nublado', help_text='Condición del clima (Soleado, Nublado, Lluvia, etc.)', max_length=100),
        ),
        migrations.AddField(
            model_name='weatherobservation',
            name='dew_point',
            field=models.FloatField(blank=True, help_text='Punto de rocío en °C', null=True),
        ),
        migrations.AddField(
            model_name='weatherobservation',
            name='feels_like_temp',
            field=models.FloatField(blank=True, help_text='Sensación térmica en °C (opcional)', null=True),
        ),
        migrations.AddField(
            model_name='weatherobservation',
            name='humidity',
            field=models.IntegerField(default=50, help_text='Humedad relativa en porcentaje'),
        ),
        migrations.AddField(
            model_name='weatherobservation',
            name='pressure',
            field=models.FloatField(default=1013, help_text='Presión atmosférica en hPa'),
        ),
        migrations.AddField(
            model_name='weatherobservation',
            name='uv_index',
            field=models.IntegerField(default=0, help_text='Índice UV'),
        ),
        migrations.AddField(
            model_name='weatherobservation',
            name='wind_speed',
            field=models.FloatField(default=0, help_text='Velocidad del viento en m/s'),
        ),
        migrations.AlterField(
            model_name='weatherobservation',
            name='temperature',
            field=models.FloatField(help_text='Temperatura en °C'),
        ),
        migrations.AddIndex(
            model_name='weatherobservation',
            index=models.Index(fields=['-timestamp'], name='weather_wea_timesta_8f96b4_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherobservation',
            index=models.Index(fields=['city', '-timestamp'], name='weather_wea_city_id_4d5517_idx'),
        ),
    ]
