# Generated by Django 5.1.14 on 2025-12-05 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_city_options_alter_weatherobservation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherobservation',
            name='dew_point',
        ),
        migrations.RemoveField(
            model_name='weatherobservation',
            name='feels_like_temp',
        ),
        migrations.RemoveField(
            model_name='weatherobservation',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='weatherobservation',
            name='pressure',
        ),
        migrations.RemoveField(
            model_name='weatherobservation',
            name='uv_index',
        ),
        migrations.RemoveField(
            model_name='weatherobservation',
            name='wind_speed',
        ),
    ]
