# Generated by Django 5.1.14 on 2025-12-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_weatherobservation_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherobservation',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Observación Meteorológica', 'verbose_name_plural': 'Observaciones Meteorológicas'},
        ),
        migrations.AlterField(
            model_name='weatherobservation',
            name='max_temperature',
            field=models.FloatField(blank=True, help_text='Temperatura máxima', null=True),
        ),
        migrations.AlterField(
            model_name='weatherobservation',
            name='min_temperature',
            field=models.FloatField(blank=True, help_text='Temperatura mínima', null=True),
        ),
    ]
