# Generated by Django 5.1.14 on 2025-12-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_alter_weatherobservation_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'Ciudad', 'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AddField(
            model_name='city',
            name='comunidad_autonoma',
            field=models.CharField(blank=True, help_text='Comunidad autónoma de España', max_length=50),
        ),
    ]
